name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: my job
    runs-on: ubuntu-latest
    strategy:
     matrix:
      os: [macos-latest, ubuntu-18.04, windows-latest]
      node: [12]
      include:
       - os: ubuntu-18.04
         node: 13
         experimental: true
         
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
